Repository hyejungg/ai-news-noti-bot, pull requests merged in 2024-03, with the labels that each got.

#6 feat/#3 몽고 디비 설정 추가
  src/config/index.ts
  src/index.ts
  src/loader/index.ts
  src/model/Message.ts
  src/model/Site.ts
  src/service/TrendService.ts
  src/types/interface/MessageInfo.ts
  tsconfig.json
Labels: enhancement

#8 feat/#4 클루잇 뉴스레터 데이터 스크래핑 추가
  .gitignore
  src/service/TrendService.ts
Labels: enhancement

#14 lambda 핸들러 단위로 프로젝트 코드 수정
  package-lock.json
  package.json
  scripts/scraper/invokeLambda.sh
  scripts/scraper/updateLambda.sh
  src/config/index.ts
  src/index.ts
  src/local.ts
  src/service/TrendService.ts
  src/types/aws/lambda.ts
Labels: enhancement

#16 정적 웹페이지 구성 및 사이트 정보 저장 API 구현
  src/api/index.ts
  src/api/readme.md
  src/api/test.ts
  src/model/Site.ts
  src/service/TrendService.ts
  src/types/interface/SiteInfo.ts
  static/postSiteForm/images/Mar-Business_18.jpg
  static/postSiteForm/index.html
Labels: enhancement

#20 삼성 sds 링크 수정
  src/service/TrendService.ts
Labels: enhancement

#23 TrendService 리팩토링
  lambdas/news-scraper/src/extractor/Extractor.ts
  lambdas/news-scraper/src/extractor/implementation/AiTimesExtractor.ts
  lambdas/news-scraper/src/extractor/implementation/ClueitExtractor.ts
  lambdas/news-scraper/src/extractor/implementation/DevoceanExtractor.ts
  lambdas/news-scraper/src/extractor/implementation/GeekNewsExtractor.ts
  lambdas/news-scraper/src/extractor/implementation/SamsungSdsExtractor.ts
  lambdas/news-scraper/src/factory/ExcractorFactory.ts
  lambdas/news-scraper/src/service/TrendService.ts
  lambdas/news-scraper/src/types/news/ClueitArchiveResponseItem.ts
Labels: enhancement

#27 폼 제출, 결과 웹페이지 모바일 최적화
  pages/postSiteForm/error.html
  pages/postSiteForm/index.html
  pages/postSiteForm/success.html
Labels: bug, enhancement

#29 form api 자동배포 추가
  .github/workflows/deploy.yml
  DockerfileApi
  pages/postSiteForm/index.html
Labels: enhancement

#31 긱뉴스 링크 변경
  lambdas/news-scraper/src/extractor/implementation/GeekNewsExtractor.ts
Labels: bug
